### ISSUE TITLE
Code Audit

### ISSUE THREAD

**Issue by wrightcj03** [a8cteam51/onbeing#1]
We'll go through our security checklist and run the theme through scanners.

**Comment by michiecat** [comment]
Items uncovered by the Theme Check plugin. https://wordpress.org/plugins/theme-check/

- [ ] Missing info in style.css header:

> REQUIRED: Version: is missing from your style.css header.
REQUIRED: Text Domain: is missing from your style.css header.
REQUIRED: License: is missing from your style.css header.
REQUIRED: License URI: is missing from your style.css header.
REQUIRED: Description: is missing from your style.css header.

**Comment by michiecat** [comment]
Once the the Pressable migration is complete, I'll import the theme into this repository and take care of these fixes.

**Comment by michiecat** [comment]
Since the theme will ultimately be rebuilt, I am going to close this out.
