### ISSUE TITLE
BUGHANCEMENT: Getty Images plug-in not working optimally

### ISSUE THREAD

**Issue by wrightcj03** [a8cteam51/onbeing#22]
The Getty Images plugin doesn't seem to recognize when images have already been downloaded by our account. When I entered an image ID for an image that had been released for download, it prompted me to insert a "comp" image. This won't work well for us unless we can insert the full-res image from within the Getty plugin. 58067dc9d3ca121569656e16False

**Comment by tgilliss** [comment]
This plug-in isn't useful and we're not using it. So, let's just remove/deactivate the plugin before migration.

**Comment by wrightcj03** [comment]
Sounds good, @tgilliss I've added it to the checklist to remove: https://github.com/a8cteam51/onbeing/issues/7

**Comment by tgilliss** [comment]
Excellent. Thank you!
T

...................
*Trent Gilliss*
Chief Content Officer, Krista Tippett Public Productions
Executive Editor, *On Being <http://onbeing.org/> + **The Civil
Conversations Project <http://civilconversationsproject.org>*

651.206.2022 / @trentgilliss <http://twitter.com/trentgilliss>

1619 Hennepin Ave S
Minneapolis, MN 55403
