### ISSUE TITLE
BUG: Blockquote overlaps headers on posts with the category "longreads"

### ISSUE THREAD

**Issue by wrightcj03** [a8cteam51/onbeing#31]
On this page, the blockquote line is overlapping the header text. This seems like a common bug we've seen in multiple places, wonder if there's an across the board fix? http://www.onbeing.org/about/becoming-wise-the-book/discussion-guide-chapter-one-of-becoming-wise/

![screenshot_2017-02-06_09 38 41](https://cloud.githubusercontent.com/assets/16471307/24471639/62ecdf1e-1488-11e7-8a59-7681708c9428.png)

**Comment by danielwrobert** [comment]
Fixed in #80
