### ISSUE TITLE
BUG: Long image credits overlap the image causing a design error

### ISSUE THREAD

**Issue by wrightcj03** [a8cteam51/onbeing#40]
We need a fix for the error shown here when the image credit is longer than the black bar. 

http://onbeing.org/programs/anoushka-shankar-stephen-mitchell-and-roberta-bondi-approaching-prayer/

![screen_shot_2016-11-30_at_4 05 23_pm](https://cloud.githubusercontent.com/assets/16471307/24466223/b915dbe2-1475-11e7-977e-709839f4b270.png)

**Comment by danielwrobert** [comment]
Fixed in #79
