### ISSUE TITLE
BUG: When there are two authors on a post, the first author's title is given for the second author.

### ISSUE THREAD

**Issue by mariahism** [a8cteam51/onbeing#50]
When there is more than one author on a post, it is copying the first author's position title to the position title of the second author. See this post: http://www.onbeing.org/blog/google-faith-formation-and-more-white-knuckle-moments-for-mormons/

Susan Leem's position title is "associate producer" but it is showing up as "executive editor" because of Trent's title.
![screenshot_2017-02-21_16 02 31](https://cloud.githubusercontent.com/assets/16471307/23965326/a02cd540-0985-11e7-8d3c-1d2aec2e67fd.png)
![screenshot_2017-02-21_16 02 44](https://cloud.githubusercontent.com/assets/16471307/23965327/a04ec97a-0985-11e7-902b-119a8f12cc38.png)

**Comment by danielwrobert** [comment]
Fixed in #81
