### ISSUE TITLE
BUG: Third music item sometimes misaligned in Books + Music section of episode pages

### ISSUE THREAD

**Issue by msambilay** [a8cteam51/onbeing#52]
Alignment of the third music item in the Books + Music section of episode pages will sometimes be thrown off. Can't quite determine cause, but will continue to investigate. Sometimes rearranging items fixes problem. See attached screenshots, and Books + Music section of [Pádraig Ó Tuama episode page](http://onbeing.org/programs/padraig-o-tuama-belonging-creates-and-undoes-us-both/).

![screen shot 2017-03-23 at 10 00 09 am](https://cloud.githubusercontent.com/assets/25963352/24254044/e31c1ab6-0faf-11e7-9976-76df34dfceb1.png)

![screen shot 2017-03-23 at 10 08 24 am](https://cloud.githubusercontent.com/assets/25963352/24254388/cb3edf2c-0fb0-11e7-8f82-1423a3488a00.png)

**Comment by danielwrobert** [comment]
Fixed in #78
