### ISSUE TITLE
Plugins to be licensed

### ISSUE THREAD

**Issue by tgilliss** [a8cteam51/onbeing#56]
Two plugins being used (ACF and ASA2) were both licensed to our previous developer, Circlesphere. The API keys are still functioning but they should be updated so now might be the time to go ahead and buy new developer licenses so we can get new access keys.

Christie or Michelle, could you take a look at https://www.advancedcustomfields.com/pro/ and https://getasa2.com/pricing/ and recommend which licenses I should purchase? Then we can get new access keys and upgrade accordingly. Thank you!

**Comment by wrightcj03** [comment]
@tgilliss Re: ASA2—I don't think you'd need anything more than the single domain license.

**Comment by michiecat** [comment]
Closing because the license has been set up.
