### ISSUE TITLE
SoundCloud playlists not embedding properly

### ISSUE THREAD

**Issue by msambilay** [a8cteam51/onbeing#59]
When creating a new episode page, in the website audio section, when I enter a URL to a SoundCloud playlist, only the link appears below the field, not the playlist itself, as it should:

![screen shot 2017-04-13 at 1 41 13 pm](https://cloud.githubusercontent.com/assets/25963352/25056111/67125d66-212c-11e7-8e65-b3c0d99a850c.png)

On the front end of the episode page, when I click on the "Play Episode" button, the player pop-up appears, but with only the link and no embedded player:

![screen shot 2017-04-13 at 1 41 49 pm](https://cloud.githubusercontent.com/assets/25963352/25056121/77664d30-212c-11e7-8fef-afc4703dfa7a.png)

On episodes published before this bug came up — while the audio is appearing and playing successfully, the pop-up only displays a single audio player, rather than the playlist containing both the produced and unedited audio:

![screen shot 2017-04-13 at 1 44 25 pm](https://cloud.githubusercontent.com/assets/25963352/25056170/b8556d62-212c-11e7-92a9-28af9d2cc7aa.png)

And, if you do not close out that pop-up window, any following clicks on "Play Episode" — even on different episode pages — will continuously load new individual audio players in that same pop-up window (screenshots of a single window):

![screen shot 2017-04-13 at 2 08 02 pm](https://cloud.githubusercontent.com/assets/25963352/25056189/dd59f722-212c-11e7-9d7e-afd7ed426703.png)
![screen shot 2017-04-13 at 2 07 55 pm](https://cloud.githubusercontent.com/assets/25963352/25056190/dd5b5252-212c-11e7-9f15-daa03960fc14.png)

**Comment by michiecat** [comment]
This turned out to be a SoundCloud issue, and the SoundCloud team fixed it last week.
