### ISSUE TITLE
Initial Audit To-dos: OnBeing Team

### ISSUE THREAD

**Issue by michiecat** [a8cteam51/onbeing#6]
- [x] Verify that all of your Pantheon and WordPress users have strong & unique passwords. See https://en.support.wordpress.com/selecting-a-strong-password/ for setting strong passwords.
- [ ] To further secure your Pantheon account, have your users set up secure logins via One Login: https://support.onelogin.com/hc/en-us/articles/204356174-Configuring-SAML-for-Pantheon
- [x] Review inactive plugins. Christie’s plugin audit will help with this.
- [ ] Remove all inactive themes except for the current default (Twenty Seventeen).
- [x] Make sure there are no users with "admin" in the username.
- [x] Review your WP users, especially the administrators, authors, and contributors -- deleting inactive users, removing unneeded administrators, etc. The number of users with admin privileges should be as low as possible. If someone isn’t using their admin account, their account should either be deleted or demoted to a non-admin role.

**Comment by wrightcj03** [comment]
@michiecat Noting here that One Login is on hold. We reviewed inactive plugins but the concierge team will need to remove them and the inactive themes via FTP.
