### ISSUE TITLE
Create newsletter subscription pop-up

### ISSUE THREAD

**Issue by wrightcj03** [a8cteam51/onbeing#60]
I'll use MailChimp's form builder to create a pop-up to promote sign-ups for the On Being newsletter: http://kb.mailchimp.com/lists/signup-forms/add-a-pop-up-signup-form-to-your-website

The form builder supplies code that we'll need to add to the theme. I'll work with @michiecat to figure out the best way to do this.

**Comment by wrightcj03** [comment]
@sarahmonster or @danielwrobert can one of you embed the following code on the test site?

`<script type="text/javascript" src="//s3.amazonaws.com/downloads.mailchimp.com/js/signup-forms/popup/embed.js" data-dojo-config="usePlainJson: true, isDebug: false"></script><script type="text/javascript">require(["mojo/signup-forms/Loader"], function(L) { L.start({"baseUrl":"mc.us4.list-manage.com","uuid":"c4ce343e5cb83e8b16dffbf08","lid":"1c66543c2f"}) })</script>`

Here's documentation (although it doesn't say much): http://kb.mailchimp.com/lists/signup-forms/add-a-pop-up-signup-form-to-your-website

**Comment by wrightcj03** [comment]
@tgilliss Can you review the pop-up on obtester.com? It will appear after 5 seconds but won't appear again if you've already viewed it so you'll have to load the link on a new private browser session to see it multiple times.
<img width="1137" alt="screen shot 2017-06-06 at 1 12 35 pm" src="https://user-images.githubusercontent.com/23107581/26847885-cccf7a68-4abb-11e7-8b9c-14536be3fd3e.png">

You'll always be able to edit the content, fields, and certain styles from MailChimp. Lists > On Being Newsletter > (click the dropdown arrow) sign up forms > pop-up form. Just publish any changes you make and the form will update on the site.

**Comment by tgilliss** [comment]
It's working for me. Thank you!
T

...................
*Trent Gilliss*
Publisher & Editor-in-Chief
*On Being <http://onbeing.org/> + **The Civil Conversations Project
<http://civilconversationsproject.org>*

651.206.2022 / @trentgilliss <http://twitter.com/trentgilliss>

1619 Hennepin Ave
Minneapolis, MN 55403
