### ISSUE TITLE
Sporadic 502 Server Error This Morning

### ISSUE THREAD

**Issue by mariahism** [a8cteam51/onbeing#63]
It's never lasting more than a few moments/minutes, but I've replicated the issue on a few different computers. If it keeps happening, I'll update.

**Comment by mariahism** [comment]
Just got a 500 error too on multiple computers:
![screenshot 2017-05-03 10 47 10](https://cloud.githubusercontent.com/assets/16471307/25669036/076cdf82-2fee-11e7-9cee-68b585c4d98a.png)

**Comment by tgilliss** [comment]
Has our team at Pressable been able to pinpoint this issue?
T

...................
*Trent Gilliss*
Publisher & Editor-in-Chief
*On Being <http://onbeing.org/> + **The Civil Conversations Project
<http://civilconversationsproject.org>*

651.206.2022 / @trentgilliss <http://twitter.com/trentgilliss>

1619 Hennepin Ave
Minneapolis, MN 55403

**Comment by michiecat** [comment]
@tgilliss -- we emailed Mariah with the details regarding this, but there were some performance issues with the site for which I will create a separate issue. I'll ping you on it with more details there.
