### ISSUE TITLE
Performance clean-up: removing 404 links

### ISSUE THREAD

**Issue by michiecat** [a8cteam51/onbeing#64]
https://github.com/a8cteam51/onbeing/search?p=2&q=itunes&type=&utf8=%E2%9C%93

Checking each link in the search above for 404s, and removing them if they 404. 404s are not cached by the server, and as a result it can lead to performance issues (and 503 errors). Since these links are already 404-ing, their removal should not have an immediate affect on the site.

cc @tgilliss @mariahism.

**Comment by michiecat** [comment]
@tgilliss These template files don't seem to be in use. Can you let me know their purposes? If they're not in use, I can go ahead and delete them.

* https://github.com/a8cteam51/onbeing/blob/302158adfcf13e32f173b0473c74ab224d3a0c41/js/single-programs.php
* https://github.com/a8cteam51/onbeing/blob/95a0a6ca367b6bbb5bf0c983e581405bcf60b17c/about.php
* https://github.com/a8cteam51/onbeing/blob/95a0a6ca367b6bbb5bf0c983e581405bcf60b17c/archive-collections.php
* https://github.com/a8cteam51/onbeing/blob/302158adfcf13e32f173b0473c74ab224d3a0c41/program.php
* https://github.com/a8cteam51/onbeing/blob/95a0a6ca367b6bbb5bf0c983e581405bcf60b17c/widget.php
* https://github.com/a8cteam51/onbeing/blob/0ecb454d0fdfa799788f0c7e8949a365d241f02c/js/single.php

These files are being loaded but are referencing a lot of missing images:

* https://github.com/a8cteam51/onbeing/blob/95a0a6ca367b6bbb5bf0c983e581405bcf60b17c/css/being.css
* https://github.com/a8cteam51/onbeing/blob/95a0a6ca367b6bbb5bf0c983e581405bcf60b17c/css/reskin.css

**Comment by michiecat** [comment]
cc @mariahism if you have any comments re the templates and files listed above. I can go ahead and delete these templates if they aren't in use.

**Comment by tgilliss** [comment]
Hey Michelle. Mariah and I both looked at them but, to be honest, it's
beyond our ken. We're not quite sure what their purpose is now, or if they
are being accessed. Perhaps you can delete and point us to any potential
places to check?

Thank you!
Trent

...................
*Trent Gilliss*
Publisher & Editor-in-Chief
*On Being <http://onbeing.org/> + **The Civil Conversations Project
<http://civilconversationsproject.org>*

651.206.2022 / @trentgilliss <http://twitter.com/trentgilliss>

1619 Hennepin Ave
Minneapolis, MN 55403

**Comment by michiecat** [comment]
@tgilliss I'm going to delete these unused template files after we've merged in the fixes the team has been working on from earlier today. The problematic 404s have already been taken care of.
