### ISSUE TITLE
Initial Audit To-dos: Concierge Team

### ISSUE THREAD

**Issue by michiecat** [a8cteam51/onbeing#7]
- [ ] Research and recommend 2FA plugins; at the least, all users with the ability to post should have 2FA enabled.
- [x] Install and configure Jetpack. Enable brute protect, VaultPress, etc.
- [ ] Fix items in the theme that were uncovered from the WP.ORG Theme Scanner.
- [x] Remove inactive plugins
- [x] Remove inactive themes
- [x] Remove the following active plugins: Freemage, Duplicate Post, Toolset Access, Getty Images

Phase 2: do an in-depth review of the theme (#5) to catch things that the theme scanner does not detect.

**Comment by michiecat** [comment]
I removed items that were host-specific; since those will be addressed after the switch takes place.

**Comment by wrightcj03** [comment]
I get the following errors when I try to update these plugins:

Yoast
"Update Failed: Download failed. Unauthorized"

WPBakery Visual Composer
"Update Failed: License is activated on another domain: http://dev-onbeingwp.pantheonsite.io"

**Comment by wrightcj03** [comment]
I get the following error when I try to remove the theme Twenty Sixteen:

"Deletion failed: Could not fully remove the theme twentysixteen."

**Comment by michiecat** [comment]
Since we are rewriting the theme, closing this as it's no longer relevant.
