### ISSUE TITLE
Incorrect blog post title appearing in Google search results

### ISSUE THREAD

**Issue by msambilay** [a8cteam51/onbeing#71]
This search result is appearing in Google for [this blog post](https://onbeing.org/blog/sharon-salzberg-a-standing-meditation-for-self-care/):
![screen shot 2017-05-23 at 10 24 17 am](https://cloud.githubusercontent.com/assets/25963352/26374598/72a3030c-3fcb-11e7-9f8c-2f123e99530e.png)

https://www.google.com/search?q=%22taking+a+stand+for%22+site%3Aonbeing.org&oq=%22taking+a+stand+for%22+site%3Aonbeing.org&aqs=chrome..69i57.8592j0j7&sourceid=chrome&ie=UTF-8

This was an old title that got changed before we published the piece, so it should not be showing up anywhere publicly. Clicking on the result brings the user to a [dead page](https://onbeing.org/blog/taking-a-stand-for-our-own-happiness/).

The result doesn't appear in a search for the correct title - but it does appear with a search for the old title and, strangely, for a search for the name of the photographer who took the old lead photo (this is how we stumbled across it - this photo has since been replaced for unrelated reasons).

**Comment by wrightcj03** [comment]
Hi @msambilay ! I 301 redirected the dead link to the one you provided via Yoast and tested that the link in your Google search now forwards correctly.
