### ISSUE TITLE
Adding SoundCloud link as a "video" in blog posts to replace the featured image breaks the formatting

### ISSUE THREAD

**Issue by mariahism** [a8cteam51/onbeing#74]
This was not happening before, but the SoundCloud links in the "video" field that replaces the featured image is now breaking the format and not reducing down correctly for responsive design. This is not happening for video links, just SoundCloud: 

https://onbeing.org/blog/from-conflict-resolution-to-conflict-transformation/
![screenshot 2017-05-31 12 07 08](https://cloud.githubusercontent.com/assets/16471307/26644127/59f723ae-45f9-11e7-9729-a6c8b2d439d5.png)
![screenshot 2017-05-31 12 07 01](https://cloud.githubusercontent.com/assets/16471307/26644128/59fb7440-45f9-11e7-9de4-2f8fae2ead56.png)

**Comment by tgilliss** [comment]
This fix doesn't seem to be working properly. When I test the link, the video embed still spills over.

**Comment by michiecat** [comment]
@tgilliss There was caching on the server which prevented the changes from showing up. I emptied the cache and I now see the fix. You may also need to clear your browser cache. If you're still unable to see the fix, let me know, as well as what browser you're using. Thanks!

**Comment by tgilliss** [comment]
Got it. Thank you.

...................
*Trent Gilliss*
Publisher & Editor-in-Chief
*On Being <http://onbeing.org/> + **The Civil Conversations Project
<http://civilconversationsproject.org>*

651.206.2022 / @trentgilliss <http://twitter.com/trentgilliss>

1619 Hennepin Ave
Minneapolis, MN 55403

On Thu, Jun 15, 2017 at 5:17 PM, Michelle Langston <notifications@github.com
