### ISSUE TITLE
Podcast Feed Failing to Refresh on iTunes Because of a Possible Server Timeout

### ISSUE THREAD

**Issue by mariahism** [a8cteam51/onbeing#75]
The podcast for this week (Brian Greene) is not showing up in iTunes: https://itunes.apple.com/us/podcast/on-being-with-krista-tippett/id150892556?mt=2

On iTunes site manager, there is a warning label next to the On Being podcast with the note (attached): "We experienced a time out connecting to this feed at this time. Read timed out." (Screenshot attached) I tried refreshing the feed directly there several times and that didn't resolve the issue. 

We've checked the podcast image size, URLs, everything we can control on the feed. I'm not sure if it's related to our other site time outs/largeness of the RSS feed, but is it possible to look into this?
![screenshot 2017-06-02 11 26 49](https://cloud.githubusercontent.com/assets/16471307/26740353/cdf6f552-479a-11e7-9e47-255fc9776243.png)

**Comment by wrightcj03** [comment]
I see Brian Greene's episodes on both the link you sent and in my Apple Podcast app. 
![img_2256](https://cloud.githubusercontent.com/assets/23107581/26755006/4001217a-4842-11e7-9996-d967418597c0.PNG)
<img width="932" alt="screen shot 2017-06-03 at 9 13 17 am" src="https://cloud.githubusercontent.com/assets/23107581/26755007/40027bf6-4842-11e7-9e27-41bf87f6fe35.png">

@mariahism Did you make any changes that might have caused it to finally upload?

**Comment by tgilliss** [comment]
We didn't make any changes, and I'm now seeing it. Perhaps this is an Apple
issue this time? We'll keep our eye on this week's and subsequent
downloads. Thank you for checking into it.
T

...................
*Trent Gilliss*
Publisher & Editor-in-Chief
*On Being <http://onbeing.org/> + **The Civil Conversations Project
<http://civilconversationsproject.org>*

651.206.2022 / @trentgilliss <http://twitter.com/trentgilliss>

1619 Hennepin Ave
Minneapolis, MN 55403

**Comment by michiecat** [comment]
@tgilliss @mariahism is this still happening for you? If not, we can close this out.

**Comment by tgilliss** [comment]
Looks good, Michelle. Please close out. Thank you!

...................
*Trent Gilliss*
Publisher & Editor-in-Chief
*On Being <http://onbeing.org/> + **The Civil Conversations Project
<http://civilconversationsproject.org>*

651.206.2022 / @trentgilliss <http://twitter.com/trentgilliss>

1619 Hennepin Ave
Minneapolis, MN 55403

On Thu, Jun 15, 2017 at 3:38 PM, Michelle Langston <notifications@github.com
