### ISSUE TITLE
BUG: Episodes can't be excluded from the XML feed without being removed from the episode roll page

### ISSUE THREAD

**Issue by wrightcj03** [a8cteam51/onbeing#9]
"Exclude from Search Results" option does not exclude a podcast episode from being included in the XML feed. In order for each repeat episode to show up on the episode roll page, it needs to be included in the "On Being with Krista Tippett" podcast series. But, if it's included in the series, then it shows up in the XML feed, which is redundant since it appears as a newer episode — even if the "exclude from search results" box is checked. I think the ideal logic would be that each episode should belong to a series, but the exclude checkbox will eliminate it from showing up in search query results and also from being added to the XML feed.

**Comment by tgilliss** [comment]
Glad to discuss this bug in more depth with you all. It's probably easier to walk you through it at some time.

**Comment by tgilliss** [comment]
Yes, this would definitely be helpful. It might take some consideration
considering that an episode for On Being or another podcast from On Being
Studios might be excluded from one feed but possibly included in another.
Having multiple versions appear in the search results is confusing for some
folks, but it's particularly troubling for some of our internal
stakeholders who want the most recent episode to be the one people are
directed to.

Re: the rebroadcast question... we don't normally indicate a rebroadcast in
the episode. And we currently don't do it on the website. But, I would like
some way of indicating the original "release date" so that people know that
it's a remix.

...................
*Trent Gilliss*
Publisher & Editor-in-Chief
*On Being <http://onbeing.org/> + **The Civil Conversations Project
<http://civilconversationsproject.org>*

651.206.2022 / @trentgilliss <http://twitter.com/trentgilliss>

1619 Hennepin Ave
Minneapolis, MN 55403

**Comment by michiecat** [comment]
@tgilliss I've been doing some digging into this and I want to confirm that I'm on the same page with you as far as desired outcome.

1. Repeat Episodes SHOULD be included in a series. 
2. You want to be able to check "Exclude from Search", and have the repeat episode also not appear in the any XML feed.
3. You want the repeat episode to appear in the roll pages (both for the month it most recently aired, like this for Joy Ladin: https://onbeing.org/programs/ pages as well as on archive pages like this where it aired previously (Joy Ladin does NOT appear currently): https://onbeing.org/programs/page/5/

Am I on the right track of understanding?

**Comment by michiecat** [comment]
@tgilliss I spent quite a bit of time digging into this and have figured out how to prevent episodes that have "Exclude from search" checked from showing up in the feed. The Search Exclude functionality comes from a plugin which is not automatically linked to Seriously Simple Podcasting. 

I have added the following function inside the loop on `feed-podcast.php`, which excludes posts that are inside the excluded posts array (from the "Search Exclude" plugin). I've been using http://dev-onbeingwp.pantheonsite.io/ to test, and have checked the hide from search option on http://dev-onbeingwp.pantheonsite.io/programs/margaret-wertheim-the-grandeur-and-limits-of-science-2/. This post does not show up in the feed (view-source:http://dev-onbeingwp.pantheonsite.io/feed/podcast/podcast).

`// If Search Exclude Plugin is active, exclude posts that have been hidden from search.
     if ( class_exists( 'SearchExclude' ) ) {
        $excluded_from_search = get_option( 'sep_exclude', array() );
	if ( in_array( get_the_ID(), $excluded_from_search ) ) {
		continue;
        }
  }`

This hasn't been added to the live site yet and I'll continue to test it further. Trent, when this new code is active, it means that when you check "Exclude from Search" on an Episode, it'll remove it from any XML feed where we've added the above code, even if you add it to a series. Is that the functionality that you were looking for?

Finally, you have multiple podcast feed templates. Did you want me to add this to ALL of your feeds: 

`feed-podcast.php`, `feed-podcast_mobile.php`, `feed-mobile.php`, `feed-extras-only.php`, `feed-extras_only.php`, `feed-episodes-only.php`, `feed-episodes_only.php`, `feed-becoming-wise.php`,

**Comment by tgilliss** [comment]
Hey Michelle--

This sounds right, I think, so let's run with this fix. And, yes, why don't we add it to all the feeds for now. If I'm wrong on this thinking, will it be problematic to pull out certain feeds?

Also, when I'm the episode roll/landing page, I notice a lot of error language like this:

"/srv/bindings/7d96d340c6f0456b9aa6c509986c30eb/code/wp-content/themes/onbeing_wp/functions.php on line 864 Warning: Missing argument 3 for modify_get_the_date() in /srv/bindings/7d96d340c6f0456b9aa6c509986c30eb/code/wp-content/themes/onbeing_wp/functions.php on line 864"

Is this just for testing?

**Comment by michiecat** [comment]
>This sounds right, I think, so let's run with this fix. And, yes, why don't we add it to all the feeds for now. If I'm wrong on this thinking, will it be problematic to pull out certain feeds?

Removing the code from certain feeds afterward won't be a problem. 

With regards to the error message, yes, that was remnants from testing for issue #10. I've remove the code that was causing the error. :)

I'll do some more testing to make sure this is all working, and will apply it to the live site. Before we make the fix live, we'll email you to give you a heads-up.

**Comment by tgilliss** [comment]
Thanks, Michelle.
T

...................
*Trent Gilliss*
Publisher & Editor-in-Chief
*On Being <http://onbeing.org/> + **The Civil Conversations Project
<http://civilconversationsproject.org>*

651.206.2022 / @trentgilliss <http://twitter.com/trentgilliss>

1619 Hennepin Ave
Minneapolis, MN 55403

On Tue, Apr 25, 2017 at 5:59 PM, Michelle Langston <notifications@github.com

**Comment by michiecat** [comment]
@tgilliss just wanted to let you know that you can now test this on obtester.com!

**Comment by michiecat** [comment]
This was addressed in the bug sprint and has been rolled into the live site. Closing for now since it was working in all of our testing. However, if you notice any issues with it we can re-open.
