### ISSUE TITLE
Expose new endpoints in API

### ISSUE THREAD

**Issue by wrightcj03** [a8cteam51/onbeing#93]
Per request, please expose the "short description" and "theme" fields for each Episode post type in the API.

**Comment by pippercameron** [comment]
Testing in https://github.com/a8cteam51/onbeing/commit/32b028f9d7b2ccd22cd3eb01e580aac8626cbdac.

**Comment by pippercameron** [comment]
Merged in https://github.com/a8cteam51/onbeing/pull/94!

**Comment by pippercameron** [comment]
Deployed and working correctly: https://onbeing.org/wp-json/wp/v2/programs/12279
