### ISSUE TITLE
Restore third column on podcast and about landing pages

### ISSUE THREAD

**Issue by wrightcj03** [a8cteam51/onbeing#97]
We lost a column on the following pages after we did your scrum a few weeks ago:

https://onbeing.org/about/
https://onbeing.org/programs/

These should be three column layouts instead of two

**Comment by tgilliss** [comment]
Hey there. Any idea when we might get this corrected? It's really messing up the user experience on some of our highest profile pages.

**Comment by michiecat** [comment]
@tgilliss I'm working on a fix for this now!

**Comment by tgilliss** [comment]
Thank you!
T

...................
*Trent Gilliss*
Editor-in-Chief / Publisher / Cofounder
*On Being <https://onbeing.org/> + On Being Studios <https://onbeing.org/>*

mobile 651.206.2022 / twitter @trentgilliss
<http://twitter.com/trentgilliss>

1619 Hennepin Ave
Minneapolis, MN 55403

On Mon, Jul 31, 2017 at 3:00 PM, Michelle Langston <notifications@github.com

**Comment by michiecat** [comment]
Hi @tgilliss, this has been fixed. You might need to clear your browser cache and/or restart your computer and clear your cache again afterward in order to see it (especially if you use Chrome since it can have pretty aggressive caching), but the fix is now in place. Please re-open this issue if you notice any other problems with the columns. Thanks!

**Comment by tgilliss** [comment]
Awesome! Thank you!
T

...................
*Trent Gilliss*
Editor-in-Chief / Publisher / Cofounder
*On Being <https://onbeing.org/> + On Being Studios <https://onbeing.org/>*

mobile 651.206.2022 / twitter @trentgilliss
<http://twitter.com/trentgilliss>

1619 Hennepin Ave
Minneapolis, MN 55403

On Mon, Jul 31, 2017 at 4:16 PM, Michelle Langston <notifications@github.com
